
trigger:
- none

pool:
  vmImage: 'ubuntu-latest'  #azure pools will work only if ACR is set to Public else it will throw 403 error

stages:
- templates: Application-Template.yml
  parameters:
    EnvironmentName: 'development'  #create environment under Pipelines with approvals and checks
    stageName: BuildAndPush
    imageName: 'flask'
    tags: '000'
    serviceConnection: 'acr_push_service_connection'
    dockerFilePath: '$(Build.SourcesDirectory)/azure-function-apps/Dockerfile'
